repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        name: Check YAML files
      - id: check-toml
        name: Check TOML files
      - id: end-of-file-fixer
        name: Ensure proper file endings
        exclude: input
      - id: trailing-whitespace
        name: Remove unnecessary whitespace from code
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Sort Python imports with isort
        args:
          - --profile
          - black
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: Format Python code with black
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.0
    hooks:
      - id: nbqa-black
        name: Format code in notebooks with black
        additional_dependencies: [black==22.12.0]
      - id: nbqa-isort
        name: Sort imports in notebooks with isort
        additional_dependencies: [isort==5.11.4]
  - repo: local
    hooks:
      - id: pylint
        name: Lint Python code with pylint
        args:
          - --errors-only
        entry: pylint
        language: system
        types: [python]
